version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'steve'
      POSTGRES_DB: 'taskdb'
    container_name: 'task'
    volumes:
      - ./postgres:/var/lib/postgresql/data